# Explore here

In [11]:
#Hacer web scrapping con requests y BeautifulSoup

import requests
from bs4 import BeautifulSoup

url = 'https://www.geeksforgeeks.org/html-tables/'
url2 = 'https://app.btgpactual.cl/mercados-en-linea'

page = requests.get(url)
page2 = requests.get(url2,headers={'User-Agent': 'Mozilla/5.0'})

soup = BeautifulSoup(page.content, 'html.parser')
soup2 = BeautifulSoup(page2.content, 'html.parser')

#print(soup.prettify())

#Obtener las tablas de la página
tables = soup.find_all('table')
tables2 = soup2.find_all('table')

#convertir las tablas en un DataFrame
import pandas as pd
df = pd.read_html(str(tables))

df

[    HTML Tags                                       Descriptions
 0     <table>  Defines the structure for organizing data in r...
 1        <tr>  Represents a row within an HTML table, contain...
 2        <th>  Shows a table header cell that typically holds...
 3        <td>  Represents a standard data cell, holding conte...
 4   <caption>  Provides a title or description for the entire...
 5     <thead>  Defines the header section of a table, often c...
 6     <tbody>  Represents the main content area of a table, s...
 7     <tfoot>  Specifies the footer section of a table, typic...
 8       <col>  Defines attributes for table columns that can ...
 9  <colgroup>  Groups together a set of columns in a table to...]

In [14]:
#Bajar archivo de la web y guardar en un archivo

url = 'https://archive.ics.uci.edu/static/public/53/iris.zip'
r = requests.get(url)

with open('iris.zip', 'wb') as f:
    f.write(r.content)

#Descomprimir el archivo
import zipfile
with zipfile.ZipFile('iris.zip', 'r') as zip_ref:
    zip_ref.extractall('iris')

#Leer el archivo descomprimido iris.data y convertirlo en dataframe
df = pd.read_csv('iris/iris.data', header=None)
df

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [22]:
#leer precios de vuelos de la web de latam.com con selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time


url = 'https://www.latamairlines.com/cl/es/ofertas-vuelos?origin=SCL&inbound=2024-07-24T12%3A00%3A00.000Z&outbound=2024-06-20T12%3A00%3A00.000Z&destination=MAD&adt=1&chd=0&inf=0&trip=RT&cabin=Economy&redemption=false&sort=RECOMMENDED'

driver = webdriver.Chrome()
driver.get(url)
time.sleep(5)

#hacer click en span para ver los precios
elemento=driver.find_element(By.ID,"FlightInfoComponent1")

for a in elemento.find_elements(By.TAG_NAME, 'div'):
    print(a.text)

16:25
SCL
Duración
12 h 45 min
11:10
+1
MAD
16:25
SCL

Duración
12 h 45 min

11:10
+1
MAD
Tarifa desde
CLP968.350
CLP968.350
CLP968.350

In [24]:
!pip install kaggle

Collecting kaggle
  Downloading kaggle-1.6.14.tar.gz (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six>=1.10 in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (2023.7.22)
Requirement already satisfied: python-dateutil in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (4.66.2)
Requirement already satisfied: python-slugify in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (2.0.5)
Requirement already satisfied: bleach in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from bleach->kaggle) (23.2)
Requirement already satisfied: webencodings in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from requests->kaggle) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/mariovilches/anaconda3/lib/python3.11/site-packages (from requests->kaggle) (3.4)
Building wheels for collected packages: kaggle
  Building wheel for kaggle (setup.py) ... done
  Created wheel for kaggle: filename=kaggle-1.6.14-py3-none-any.whl size=105123 sha256=3f95a37765866a420abdc670bc2ae1c2523eab3befdf569c7f95678601d411a8
  Stored in directory: /Users/mariovilches/Library/Caches/pip/wheels/ec/d9/04/93be57edf3835182a8e76d8ff87f7e77a0113f473ba3721ee0
Successfully built kaggle
Installing collected packages: kaggle
Successfully installed kaggle-1.6.14

In [27]:
#Bajar un dataset de Kaggle usando la API de Kaggle
import os
#os.environ['KAGGLE_USERNAME'] = "mariovilches"
#os.environ['KAGGLE_KEY'] = "46a76f28991b65d7d7fec1be70e6b0fe"

#leer archivo kaggle.json
import json
with open('/Users/mariovilches/Downloads/kaggle.json', 'r') as file:
    kaggle_json = json.load(file)

os.environ['KAGGLE_USERNAME'] = kaggle_json['username']
os.environ['KAGGLE_KEY'] = kaggle_json['key']

#Descargar el dataset de Titanic haciendo un request a la API de Kaggle
import kaggle
kaggle.api.authenticate()
kaggle.api.dataset_download_files('heptapod/titanic', path='titanic', unzip=True)

#Leer el archivo descomprimido train.csv y convertirlo en dataframe
df = pd.read_csv('titanic/train_and_test2.csv')
df

Dataset URL: https://www.kaggle.com/datasets/heptapod/titanic

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0